### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by sunfishcode** [sunfishcode/wasi-preview2#1]
- [x] Update WASI APIs to use wit:
      - [x] wasi-clocks
      - [x] wasi-random
      - [x] wasi-filesystem
      - [x] wasi-sockets
      - [ ] Add handle value imports for default clocks to wasi-clocks
      - [x] #2

      - [ ] Define a `preopen` resource and update wit APIs to define subtypes of it
          - [ ] wasi-filesystem
          - [ ] wasi-sockets

 - [ ] Design and implement the needed [wit-bindgen] features:
      - [ ] Resource subtyping (single-parent only)
          - [ ] wit syntax
          - [ ] canonical ABI implementation (rust-wasm, c, wasmtime)
      - [ ] Support for producing bindings for multiple wit files at once, so that they can share types and resources
          - [ ] Design a user-interface
          - [ ] Implement it
      - [ ] Streams
          - [ ] wit syntax
          - [ ] canonical ABI implementation (rust-wasm, c, wasmtime)
             - [ ] support for reading and writing
             - [ ] support for blocking until read and write complete
             - [ ] support for creating the stdout stream
             - [ ] support for consuming and producing stream "end values"
      - [ ] Value-imports and value-exports
           - [x] wit syntax
           - [ ] canonical ABI implementation (rust-wasm, c, wasmtime)
           - [ ] design a way to indicate which imports are environment variables ("default"" keyword?)
              - [ ] implement it
      - [ ] Zero-level exports
           - [ ] wit syntax
           - [ ] canonical ABI implementation (rust-wasm, c, wasmtime)
      - [ ] Canonical ABI for the component start
           - [ ] design an ABI for this
           - [ ] implement it (rust-wasm, c, wasmtime)

 - [ ] Static Executable support
    - [ ] Merge default-visibility with wasm-export
      - [ ] Make `__attribute__((export_name("...")))` unset `WASM_SYMBOL_VISIBILITY_HIDDEN`
      - [ ] Make `__attribute__((visibility("default")))` set `WASM_SYMBOL_EXPORTED`

    - [ ] add -mexec=model=allocator
      - [ ] It behaves mostly like `-mexec-model=reactor` does today
      - [ ] exports memory/table/stack-pointer
      - [ ] It should use crt1-allocator.o instead of crt1-reactor.o

    - [ ] add -mexec-model=executable, which is not the default yet
      - [ ] think about how we'll make it import the memory/table/stack-pointer in the dynamic-linking future
      - [ ] *disallow* all exports other than `ctors_and_main`
      - [ ] rename the "memory" export to "__memory"

    - [ ] add -mexec=model=old-reactor, -mexec-model=old-command as aliases for their non-old things, which will be deprecated in the future

    - [ ] add a way to declare needed environment variables. Either in the source
          code or as linker flags.

 - [ ] Library implementations
    - [ ] write a liballoc
      - [ ] malloc impl
      - [ ] atexit/__cxa_atexit/etc. impl
      - [ ] crt1-allocator.o
    - [ ] Remove allocator features from libc
    - [ ] Teach wasm-ld to link in the allocator library
    - [ ] create a new crt1-executable.s file which calls `__wasm_call_ctors` so that wasm-ld doesn't auto-wrap all exports.

 - [ ] Dynamic linking preparedness
    - [ ] Make -static not the default mode, and make the sysroot be the thing that decides whether to have a libc.a or a libc.so
    - [ ] add -mexec-model=dll as an alias for -shared
    - [ ] copy -mexec-model=reactor's behavior for most things
    - [ ] make -fpic/fPIC/fPIE/fpie no-ops for now
    - [ ] make -rdynamic, -export-dynamic, and -export-all errors
    - [ ] rename the "memory" export to "__memory"

 - [ ] Port wasi-libc (on a branch, initially)
     - [ ] Use wit-bindgen to Generate C headers from wit-bindgen.
     - [ ] Port the wasi-libc code to the new ABI

    - [ ] Implement the [Typed Main](TypedMain.md) design in the libc startup code.
       - [ ] [Stderr](Stderr.md)
       - [ ] command-line arguments
       - [ ] preopens
           - [ ] UUIDs and command-line argument and environment-variable editing

    - [ ] Implement the preview1 API in terms of prevew2 functions.

 - [ ] Wasmtime implementation
     - [ ] Implement the new Typed Main way of running programs (see below)
     - [ ] Change how the wasmtime CLI works to be driven by wit-bindgen
     - [ ] Implement the APIs using the new wit-bindgen bindings and the
           bookkeeping plus synchronous calls implementation technique:
        - [ ] wasi-filesystem
        - [ ] wasi-clocks
        - [ ] wasi-random
        - [ ] wasi-sockets
        - [ ] wasi-poll
     - [ ] Implement the new preopen scheme
     - [ ] Implement `canonical_abi_exit`, the way for a program to exit, in Wasmtime
 - [ ] Update wit-abi and wit-abi-up-to-date for Wasmtime API changes
 
[wit-bindgen]: https://github.com/bytecodealliance/wit-bindgen
